### PR TITLE
add support for UPM

### PR DESCRIPTION
**Pull request by anatawa12**

### CODE REVIEW

**Comment by anatawa12** [comment]
VPM will use UPM so I think this is useful in the feature. The package.json I added includes configuration for VPM.

**Comment by scarletcafe** [comment]
Thanks for the PR.

**Comment by anatawa12** [comment]
Sorry, I forgot to mention. If possible, can you create new release (1.1.1)? I want a tag (version) that includes package.json.

**Comment by scarletcafe** [comment]
Done.

**Comment by anatawa12** [comment]
Thank you

**Pull request merged**
